version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
